name: Deploy React App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build React app
        run: npm run build
      
      - name: Prepare deployment directory
        run: |
          mkdir -p deploy
          cp -r react-build/* deploy/
          cp -f styles.css deploy/
          cp -f profile.jpg deploy/
          cp -f favicon.ico deploy/
          cp -f robots.txt deploy/
          cp -f CNAME deploy/
          cp -f 403.html deploy/
          cp -f non-react-index.html deploy/
          cp -f before-react-script.js deploy/
          cp -rf blocked-build deploy/blocked 2>/dev/null || true
          cp -f blocked-build/index.html deploy/Blocked.html 2>/dev/null || true
          cp -rf images deploy/ 2>/dev/null || true
          cp -rf data deploy/ 2>/dev/null || true
          cp -rf .well-known deploy/ 2>/dev/null || true
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'deploy'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4