name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      
      - name: Inject secrets into HTML
        run: |
          # Replace placeholders in index.html with actual secrets
          sed -i "s/{{SORYN_USER}}/${{ secrets.SORYN_USER }}/g" index.html
          sed -i "s/{{SORYN_PASS}}/${{ secrets.SORYN_PASS }}/g" index.html
          sed -i "s/{{GUEST_USER}}/${{ secrets.GUEST_USER }}/g" index.html
          sed -i "s/{{GUEST_PASS}}/${{ secrets.GUEST_PASS }}/g" index.html
          sed -i "s/{{JSONBIN_API_KEY}}/${{ secrets.JSONBIN_API_KEY }}/g" index.html
          sed -i "s/{{JSONBIN_BIN_ID}}/${{ secrets.JSONBIN_BIN_ID }}/g" index.html
          sed -i "s/{{IMGBB_API_KEY}}/${{ secrets.IMGBB_API_KEY }}/g" index.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2