name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      
      - name: Inject secrets into HTML
        env:
          SORYN_USER: ${{ secrets.SORYN_USER }}
          SORYN_PASS: ${{ secrets.SORYN_PASS }}
          GUEST_USER: ${{ secrets.GUEST_USER }}
          GUEST_PASS: ${{ secrets.GUEST_PASS }}
          JSONBIN_API_KEY: ${{ secrets.JSONBIN_API_KEY }}
          JSONBIN_BIN_ID: ${{ secrets.JSONBIN_BIN_ID }}
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
        run: python .github/scripts/inject_secrets.py
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2